### ISSUE TITLE
Initial review and release to NPM of FlowForge theme for Node-RED 

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-nr-theme#8]
### Current Behavior

Theme is now ready for review along side the following 2 PRs...
* https://github.com/flowforge/flowforge/pull/613
* https://github.com/flowforge/flowforge-nr-launcher/pull/37

TO DO...
* SRC code review
* Test run
* Publish

### Environment

- FlowForge version: 0.7 (target)

**Comment by knolleary** [comment]
Having used the theme for a couple days, the only tweak I'd suggest is the menu item separator:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/51083/176379103-49e7eaeb-a799-439d-8a92-24db4de781e5.png">

<img width="271" alt="image" src="https://user-images.githubusercontent.com/51083/176379506-13880def-322a-4d80-9296-e3d3d602bdb3.png">


I'd suggest sticking to the original colour that's a bit more muted against the dark/light menu backgrounds.

**Comment by Steve-Mcl** [comment]
> Just trying to tie up issues here, is this the delivery of [flowforge/flowforge#214](https://github.com/flowforge/flowforge/issues/214)

Related - in that there can be no theme choice without a theme :).

**Comment by Steve-Mcl** [comment]
> I'd suggest sticking to the original colour that's a bit more muted against the dark/light menu backgrounds.

@knolleary 
Addressed in #10 - please review & merge if happy.

**Comment by knolleary** [comment]
Looks great.

I think we're good to publish.
